### ISSUE TITLE
CS lines apparently faulty.

### ISSUE THREAD

**Issue by rusticfeel** [NyanBlade/BeatSaberQuestInstaller#44]
Serializing all assets...
File sharedassets18.assets has changed, writing new contents.
Exception writing assets file sharedassets18.assets (Sequence contains no matching element    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuestomAssets.AssetsChanger.AssetsFile.GetFileIDForFilename(String filename) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 252
   at QuestomAssets.AssetsChanger.AssetsFile.GetFileIDForFile(AssetsFile file) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 247
   at QuestomAssets.AssetsChanger.SmartPtr`1.get_FileID() in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\SmartPtr.cs:line 125
   at QuestomAssets.AssetsChanger.SmartPtr`1.WritePtr(AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\SmartPtr.cs:line 176
   at QuestomAssets.AssetsChanger.Extensions.Write[T](ISmartPtr`1 ptr, AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\Extensions.cs:line 50
   at QuestomAssets.BeatSaber.BeatmapLevelDataObject.Write(AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\BeatSaber\BeatmapLevelDataObject.cs:line 126
   at QuestomAssets.AssetsChanger.AssetsFile.Write(Stream outputStream) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 155
   at QuestomAssets.BeatSaber.Extensions.WriteCombinedAssets(IAssetsFileProvider fp, AssetsFile assetsFile, String assetsFilePath) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\BeatSaber\Extensions.cs:line 73
   at QuestomAssets.AssetsChanger.AssetsManager.WriteAllOpenAssets() in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsManager.cs:line 142
Something went horribly wrong (Sequence contains no matching element    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuestomAssets.AssetsChanger.AssetsFile.GetFileIDForFilename(String filename) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 252
   at QuestomAssets.AssetsChanger.AssetsFile.GetFileIDForFile(AssetsFile file) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 247
   at QuestomAssets.AssetsChanger.SmartPtr`1.get_FileID() in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\SmartPtr.cs:line 125
   at QuestomAssets.AssetsChanger.SmartPtr`1.WritePtr(AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\SmartPtr.cs:line 176
   at QuestomAssets.AssetsChanger.Extensions.Write[T](ISmartPtr`1 ptr, AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\Extensions.cs:line 50
   at QuestomAssets.BeatSaber.BeatmapLevelDataObject.Write(AssetsWriter writer) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\BeatSaber\BeatmapLevelDataObject.cs:line 126
   at QuestomAssets.AssetsChanger.AssetsFile.Write(Stream outputStream) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsFile.cs:line 155
   at QuestomAssets.BeatSaber.Extensions.WriteCombinedAssets(IAssetsFileProvider fp, AssetsFile assetsFile, String assetsFilePath) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\BeatSaber\Extensions.cs:line 73
   at QuestomAssets.AssetsChanger.AssetsManager.WriteAllOpenAssets() in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\AssetsChanger\AssetsManager.cs:line 142
   at QuestomAssets.QuestomAssetsEngine.UpdateConfig(BeatSaberQuestomConfig config) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\QuestomAssets\QuestomAssetsEngine.cs:line 705
   at BeatmapAssetMaker.Program.FolderMode(FolderMode args) in C:\Users\VR\Desktop\platform-tools_r28.0.3-windows\code\QuestStopgap\BeatMapAssetMaker\Program.cs:line 305
if everything didn't go perfectly in the steps above, ctrl-c now before beatsaber gets uninstalled...
Press any key to continue . . .

**Comment by rusticfeel** [comment]
This happened out of the blue when I was using version 0.7 and so i thought i would reinstall it with the new version so i deleted everything and then installed the new version and apparently there was the same problem. ^^^
