### ISSUE TITLE
Not entirely certain what the specific issue is (Won't Install)

### ISSUE THREAD

**Issue by Labarynth** [NyanBlade/BeatSaberQuestInstaller#9]
Attempting to pull Beat Saber from your device...
adb: error: failed to get feature set: no devices/emulators found
Overwrite .\backup\base.apk? (Yes/No/All): n
        0 file(s) copied.
Attempting to pull your scores...
adb: error: failed to get feature set: no devices/emulators found
The system cannot find the file specified.
The process tried to write to a nonexistent pipe.
I: Using Apktool 2.4.0 on base.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
        ... 3 more
Caused by: java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1343)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 6 more
The system cannot find the path specified.
Attempting to convert your songs for Quest...
2019/05/31 20:10:14 No info.json found in "ToConvert\10653-11218", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\11752-12511", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\122-69", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\12506-13379", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\10448-10984", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\10584-11224", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\10485-11031", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\10590-11145", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\13424-14461", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\1460-1021", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\1567-1101", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\1592-1122", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\14660-15862", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\15000-16235", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\15249-16519", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\1528-1072", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\1707-1199", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\2260-1566", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\19-3", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\197-118", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\21-4", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\2127-1472", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\3492-2574", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\2435-5757", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\2597-1808", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\2805-1977", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\3477-2556", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\3502-2588", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\496-307", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\4997-4359", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\3647-2762", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\3679-2801", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\41-17", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\4786-4104", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\5414-4844", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\5529-4986", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\7008-6703", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\5536-4982", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\5681-5137", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\574-364", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\644-415", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\703-463", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\7194-7183", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\8703-9888", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\8849-9078", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\7217-6948", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\7605-7462", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\81-41", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\8242-8316", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\8853-9083", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\9746-10154", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\9974-10444", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\Aika & Kotori - Starscream", skipping!
2019/05/31 20:10:14 No info.json found in "ToConvert\One More Time", skipping!
Changing names of songs and covers
Binary file to patch doesn't exist!
Found 5 custom songs to inject:
Couldn't find sharedassets17.assets(.split0) in the assetsFolder.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
.\assets\*.*
The system cannot find the file specified.
        0 file(s) copied.
I: Using Apktool 2.4.0
brut.directory.PathNotExist: apktool.yml
jarsigner: unable to open jar file: .\apk\base\dist\base.apk
if everything didn't go perfectly in the steps above, ctrl-c now before beatsaber gets uninstalled...
Press any key to continue . . .

**Comment by wraithguardomega** [comment]
having the same issue with v4, "The system cannot find the path specified." all over the place. version 2 works fine. and i tried to run 4 on a completely fresh install of beat saber...

**Comment by UESTC-official** [comment]
Make sure you enable Developer Mode ~

**Comment by sjb933** [comment]
I'm having this same issue, it's not related to developer mode - I certainly have that enabled and have installed plenty via SideQuest.

**Comment by sjb933** [comment]
Do not skip the install java step.  I had java installed already and tried to skip this, ran into issues like this.

**Comment by Labarynth** [comment]
As an addition , when I press any key to perform install it says device offline for some reason. And in response to Wraithgaurdomega version 2 does not work either for me
